steps:
  # Step to add the new user 'yoctouser'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        useradd -m yoctouser
        echo "User yoctouser created successfully."
        # List the user to confirm creation
        id yoctouser
        chown -R yoctouser:yoctouser /workspace
        echo "Changed ownership of /workspace to yoctouser."

  - name: 'gcr.io/sdserver-384505/yocto-builder'
    args: ['./runall.sh', 'MySSID','mypassword']

