steps:
  # Step to add the new user 'yoctouser'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        useradd -m yoctouser || true  # '|| true' to ignore if the user already exists
        # Additional commands to set up 'yoctouser', if necessary

  # Step to change ownership of the /workspace directory
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - chown -R yoctouser:yoctouser /workspace

  - name: 'gcr.io/sdserver-384505/yocto-builder'
    args: ['./runall.sh', 'MySSID','mypassword']

