steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'download-cache'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      if gsutil -q stat gs://gpi_images/geraldpi-cache.tar.gz; then
        gsutil cp gs://gpi_images/geraldpi-cache.tar.gz .
        echo "Unzipping Cache"
        tar xzf geraldpi-cache.tar.gz
        rm geraldpi-cache.tar.gz
      else
        echo "No cache found, proceeding without cache"
      fi
  # Step to add the new user 'yoctouser'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        useradd -m yoctouser
        echo "User yoctouser created successfully."
        # List the user to confirm creation
        id yoctouser
        chown -R yoctouser:yoctouser /workspace
        echo "Changed ownership of /workspace to yoctouser."

  - name: 'gcr.io/sdserver-384505/yocto-builder'
    args: ['./runall.sh', '$_MY_SSID','$_MY_PASSWORD']

  # Save outputs images
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'copy-artifacts-to-gcs'
    args:
      - 'cp' 
      - 'geraldpi-artifacts.tar.xz' 
      - 'gs://gpi_images/'

  # Cache Build Artifacts to speed up future builds
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'copy-cache-to-gcs'
    args:
      - 'cp' 
      - 'geraldpi-cache.tar.gz' 
      - 'gs://gpi_images/'

options:
  # Specify a machine type depending on your build's resource requirements
  # This is optional; if not specified, Cloud Build uses a default machine type
  machineType: 'E2_HIGHCPU_8'

timeout: 15000s
